service:
  - docker

before_install:
  - docker build -t raphaelmeyer/arch-clang-ninja .travis

script:
  - >
    docker run --rm
    --mount type=volume,source=workspace,destination=/workspace
    --mount type=bind,source=$TRAVIS_BUILD_DIR,destination=/source,readonly
    -e WORKSPACE='/workspace'
    raphaelmeyer/arch-clang-ninja /source/build

after_script:
  - docker volume rm workspace
